# Generated by Django 3.0.6 on 2020-05-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
